#!/bin/bash


if [[ "$HOSTNAME" == "login"* ]] ; then

  . /work/03754/tsmith/gcm-contrib/bash-scripts/bashrc_tacc

elif [[ "$HOSTNAME" == "pfe"* ]] ; then

  . /nobackupp2/tasmit12/gcm-contrib/bash-scripts/bashrc_pfe

elif [[ "$HOSTNAME" == "sverdrup"* ]] ; then

  . /home/tsmith/gcm-contrib/bash-scripts/bashrc_sverdrup

elif [[ "$HOSTNAME" == "ekman"* ]] ; then

  source /workspace/gcmpack/gcm-contrib/bash-scripts/bashrc_ekman

elif [ "$USER" == "tim" ] ; then

  . /Users/tim/work/gcm-contrib/bash-scripts/bashrc_mac

fi

# -------------------------------------------------------------
# All machines
# -------------------------------------------------------------

### Add local bin/lib to path ### 
export PATH=$PATH:$HOME/local/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib

### CVS Stuff ###
export CVSROOT=':pserver:cvsanon@mitgcm.org:/u/gcmpack'
export CVSEDITOR=vim

## Misc commands and specs ##
alias cdh='cd $HOME'
alias cdw='cd $WORK'
alias cdc='cd $contrib'
alias cdm='cd $mitgcm'
if [[ "$HOSTNAME" != "ekman"* ]] ; then
  alias cds='cd $SCRATCH'
fi

if [ "$USER" != "tim" ] ; then
  alias ls='ls -G --color=auto' 
else
  alias ls='ls -G'
fi
alias ll='ls -alh'
