#!/bin/bash 

## set terminal
export TERM=xterm-256color

## Modules
#module load c7 # not available
module load intel
module load openmpi

## Directories
export HOME=/home/tsmith
export SCRATCH=/scratch/tsmith
export contrib=/home/tsmith/gcm-contrib
export computing=/home/tsmith/computing
export MPI_INC_DIR=$MPI_DIR/include
export ph_data=/scratch/heimbach/data
export ase=/scratch/tsmith/MITgcm_c66i+/ase
export pig=/scratch/tsmith/MITgcm_c66i+/pig
export mitgcm=~/MITgcm_c66i+

## Commands
export PS1='[\h \W]\$ '
alias scpthorne='scp -P 8704'
alias qu='squeue -u tsmith'
alias cda='cd $ase'

## Increase stack size
ulimit -s hard
ulimit -u hard

## Netcdf workaround
#NETCDF C
export NETCDFC_ROOT=/share/netcdf-4.4.1.1/
export NETCDFC_INC=$NETCDFC_ROOT/include
export NETCDFC_BIN=$NETCDFC_ROOT/bin
export NETCDFC_LIB=$NETCDFC_ROOT/lib
#NETCDF Fortran
export NETCDFF_ROOT=/share/netcdf-fortran-4.4.4
export NETCDFF_INC=$NETCDFF_ROOT/include
export NETCDFF_BIN=$NETCDFF_ROOT/bin
export NETCDFF_LIB=$NETCDFF_ROOT/lib

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NETCDFC_LIB:$NETCDFF_LIB
export PATH=$PATH:$NETCDFC_BIN:$NETCDFF_BIN:$PATH
export INCLUDE=$INCLUDE:$NETCDFC_INC:$NETCDFF_INC

### Expand environment variables in tab completion ###
shopt -s direxpand
