#! /bin/bash

## tmux ftw
#tmux source-file /Users/tim/work/gcm-contrib/bash-scripts/tmux.conf

## Other machines
alias ekman='mosh --ssh="ssh -p 8704" ekman.ices.utexas.edu'
alias rsyncek="rsync -ave 'ssh -p 8704'"
alias scpek="scp -P 8704"
alias sshek="ssh -p 8704 ekman.ices.utexas.edu"
alias arctowski='mosh --ssh"ssh -p 8704" arctowski.ices.utexas.edu'
alias amundsen='mosh --ssh"ssh -p 8704" amundsen.ices.utexas.edu'
alias nansen='mosh --ssh"ssh -p 8704" nansen.ices.utexas.edu'

## Directories
export HOME=/Users/tim
export WORK=/Users/tim/work
export contrib=$WORK/gcm-contrib
export computing=$WORK/computing
export write_repo=$WORK/write-repo

## Nonlocal directories
export thamoc=/workspace/gcmpack/gcm-contrib/samoc

## Path and LD_LIBRARY
export PATH=$PATH:/Library/TeX/Distributions/Programs/texbin

### For MITgcm ###
export CVSROOT=':pserver:cvsanon@mitgcm.org:/u/gcmpack'
export CVSEDITOR=vim

## Commands
export PS1='[tim \W]\$ '
alias o='open'
