#!/bin/bash


if [ "$HOSTNAME" == "login2" ] ; then

  . /work/03754/tsmith/gcm-contrib/bash-scripts/bashrc_tacc

elif [[ "$HOSTNAME" == "pfe"* ]] ; then

  . /nobackupp2/tasmit12/gcm-contrib/bash-scripts/bashrc_pfe

elif [[ "$HOSTNAME" == "sverdrup"* ]] ; then

  . /home/tsmith/gcm-contrib/bash-scripts/bashrc_sverdrup

elif [ "$HOSTNAME" == "Timothys-MacBook-Pro.local" ] ; then

  . /Users/tim/work/gcm-contrib/bash-scripts/bashrc_mac

fi

# -------------------------------------------------------------
# All machines
# -------------------------------------------------------------

### Add local bin/lib to path ### 
PATH=$PATH:$HOME/local/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib

### CVS Stuff ###
export CVSROOT=':pserver:cvsanon@mitgcm.org:/u/gcmpack'
export CVSEDITOR=vim

## Misc commands and specs ##
alias cdh='cd $HOME'
alias cdw='cd $WORK'
alias cdc='cd $contrib'
alias cds='cd $SCRATCH'
alias cdm='cd $mitgcm'

alias ls='ls -G --color=auto' 
alias ll='ls -alh'
