#!/bin/bash

## Set up suffix for adjoint run: "_ad"
#  or leave as "" for forward run
suff=""
dir_suff=".hflux.m10"
perturbation="hf-perturbation"
use_masks="true"
extra_ctrls="true"
use_clim_relax="true"

## Set up directories
root_dir=$HOME/MITgcm_c65x+
ver_dir=$root_dir/verification/global_oce_llc90

exp_dir=$PWD
build_dir=$exp_dir/build$suff
code_dir=$exp_dir/code$suff

run_dir=$exp_dir'/run'$suff$dir_suff
input_dir=$exp_dir/input$suff$dir_suff

masks_dir=$input_dir/masks
perturb_dir=$input_dir/$perturbation
clim_relax_dir=$input_dir/clim

submit_script=$exp_dir/submit_samoc$suff
data_dir=$SCRATCH/data
ctrl_dir=$data_dir/control-vectors-zero
input_data_dir=$ph_data/data_v4/input_obs/input_insitu
forcing_dir=$data_dir/forcing_baseline2

# ----- 1. Set up directories and submission script
## Make work directory in SCRATCH
if [ ! -d $run_dir ] ; then
	echo "Making "$run_dir" ..."
        mkdir $run_dir
	mkdir $run_dir/diags
	mkdir $run_dir/tapes
	mkdir $run_dir/profiles
fi       

####
## Link ALL of the files
####
cd $run_dir
echo "Grabbing necessary files ..."

cp $submit_script .

#--- 2. linking binary ---------
ln -s ${ver_dir}/input_fields/*.bin .
ln -s ${ver_dir}/input_fields/wt_ones.data .
ln -s ${ver_dir}/input_fields/tile*.mitgrid .
#  ###
ln -s ${ver_dir}/input_fields/smooth2Dscales001${extsmooth} ./smooth2Dscales001
ln -s ${ver_dir}/input_fields/smooth3DscalesH001${extsmooth} ./smooth3DscalesH001
ln -s ${ver_dir}/input_fields/smooth3DscalesZ001 ./
ln -s ${ver_dir}/input_fields/smooth2Dnorm001${extsmooth}.data ./smooth2Dnorm001.data
ln -s ${ver_dir}/input_fields/smooth3Dnorm001${extsmooth}.data ./smooth3Dnorm001.data
ln -s ${ver_dir}/input_fields/smooth2Dnorm001.meta ./
ln -s ${ver_dir}/input_fields/smooth3Dnorm001.meta ./
#=================================================================================

#--- 2.1. ECCO control vectors -----
ln -s ${ver_dir}/input_fields/xx_* .
#=================================================================================

#--- 2.2 Insitu observations ------
ln -s ${input_data_dir}/*.nc .
#=================================================================================

#--- 3. linking forcing dir ------
ln -s $forcing_dir ./
#=================================================================================

#--- 4. NAMELISTS ---------
ln -s ${input_dir}/* ./
#=================================================================================

#--- 5. executable --------
ln -sf ${build_dir}/mitgcmuv${suff} ./
#=================================================================================

#--- 6. pickups -----------
#NOTE: for pickup: copy instead of link to prevent accidental over-write
cp -f ${ver_dir}/input_fields/pickup* ./
#=================================================================================

#--- 7. Copy additional control vectors for this experiment, if dir exists
if [ ! "$extra_ctrls" == "" ] ; then
  if [ -d $ctrl_dir ] ; then 
    ln -sv $ctrl_dir/* .
  else
    echo "** No additional control vectors ... "
  fi
else 
  echo "** Extra controls not added ... "
fi
#=================================================================================

#--- 8. Look for perturbation directory
if [ ! "$perturbation" == "" ] ; then
  if [ -d $perturb_dir ] ; then
    ln -sfv $perturb_dir/* .
  else
    echo "** Could not find perturbation directory: $perturb_dir ... "
  fi
else 
  echo "** Perturbations not added ... " 
fi
#=================================================================================

#--- 9. Copy masks for this particular setup.
#  dir should be inside inputs
if [ ! "$use_masks" == "" ] ; then
  if [ -d $masks_dir ] ; then
    ln -sv $masks_dir/* .
  else
    echo "** Could not find mask dir: $masks_dir ... "
  fi
else
  echo "** Masks not used ... "
fi
#=================================================================================

#--- 10. link to climatological relaxation
#  dir should be inside inputs
if [ ! "$use_clim_relax" == "" ] ; then
  if [ -d $clim_relax_dir ] ; then
    ln -sv $clim_relax_dir/* .
  else
    echo "** Could not find clim_relax dir: $clim_relax_dir ... "
  fi
else
  echo "** Climatological relaxation not used ... "
fi
#=================================================================================

echo "Ready to execute ..."

echo ""
echo "*** Pro tips: "
echo "      - Check data.pkg: useAUTODIFF = .true.? usePROFILES = .false.? "
echo ""
echo "      - Check data: "
echo "           nTimeSteps correct? tapes directory uncommented? adjDump = false?"
echo ""
echo "      - Check data.ctrl ... mult = 0 for non-optimize run? "
echo "           have the necessary xx_<parameter> files?"
echo ""
echo "      - Check data.diagnostics: have the filenames set with diags/ prefix? "
echo ""
echo "      - Check data.exf: directory set for correct forcing files? period correct?"
echo "" 
echo "      - Check data.ecco: ... just make sure it looks good"
echo ""
echo "      - Check to make sure any masks are set properly ... "
echo ""
echo "      - Check submit file for .."
echo "           Correct queue? "
echo "           forward run: <exec> mitgcmuv "
echo "           adjoint: <exec> mitgcmuv_ad "
echo "           walltime correct? " 
echo ""
echo "Assuming this is done, ready for launch ... "
echo ""
echo ""
