#!/bin/bash
#
# $Header: /u/gcmpack/MITgcm/tools/build_options/linux_amd64_ifort+mpi_ice_nas,v 1.12 2013/07/22 18:40:45 jmc Exp $
# $Name:  $

# module load comp-intel/2012.0.032 mpi-sgi/mpt.2.06a67 netcdf/4.0
# module load comp-intel/2013.1.117 mpi-sgi/mpt.2.10r6 netcdf/4.1.2
# module load comp-intel/2015.0.090 mpi-sgi/mpt.2.12r26 netcdf/4.1.2

FC=ifort
CC=icc

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'
CPP='/lib/cpp  -traditional -P'
EXTENDED_SRC_FLAG='-132'
OMPFLAG='-openmp'
CFLAGS='-fPIC'
LDADD='-shared-intel'

#LIBS='-L/nasa/sgi/mpt/2.06a67/lib -lmpi -L/nasa/netcdf/4.0/lib -lnetcdf'
#INCLUDES='-I/nasa/sgi/mpt/2.06a67/include -I/nasa/netcdf/4.0/include'
#INCLUDEDIRS='/nasa/sgi/mpt/2.06a67/include'
##- used for parallel (MPI) DIVA
#MPIINCLUDEDIR='/nasa/sgi/mpt/2.06a67/include'
#
#LIBS='-L/nasa/sgi/mpt/2.11r13/lib -lmpi -L/nasa/netcdf/4.1.2/lib -lnetcdf'
#INCLUDES='-I/nasa/sgi/mpt/2.11r13/include -I/nasa/netcdf/4.1.2/include'
#INCLUDEDIRS='/nasa/sgi/mpt/2.11r13/include'
##- used for parallel (MPI) DIVA
#MPIINCLUDEDIR='/nasa/sgi/mpt/2.11r13/include'

LIBS='-L/nasa/sgi/mpt/2.12r26/lib -lmpi -L/nasa/netcdf/4.1.2/lib -lnetcdf'
INCLUDES='-I/nasa/sgi/mpt/2.12r26/include -I/nasa/netcdf/4.1.2/include'
INCLUDEDIRS='/nasa/sgi/mpt/2.12r26/include'
#- used for parallel (MPI) DIVA
MPIINCLUDEDIR='/nasa/sgi/mpt/2.12r26/include'

#MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'

#NOOPTFLAGS='-O0 -fPIC'
NOOPTFLAGS='-O1 -fp-model precise'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS="$FFLAGS -fPIC -W0 -WB -convert big_endian -assume byterecl -align"
#    FOPTIM='-O2 -ip -fp-model precise -axSSSE4.2,SSSE3 -traceback -ftz'
    FOPTIM='-O2 -ip -fp-model precise -axAVX -xSSE4.1 -traceback -ftz'
    NOOPTFILES='seaice_growth.F calc_oce_mxlayer.F fizhi_lsm.F fizhi_clockstuff.F'
else
    #  Try to follow IEEE-754
#    FFLAGS="$FFLAGS -fPIC -w95 -W0 -WB -convert big_endian -assume byterecl -noalign"
    FFLAGS="$FFLAGS -fPIC -W0 -WB -convert big_endian -assume byterecl -noalign"
    FOPTIM='-O0'
fi
#- might want to use '-r8' for fizhi pkg:
#FFLAGS="$FFLAGS -r8"

#- For really big executable (> 2 GB), uncomment following 2 lines
FFLAGS="$FFLAGS -mcmodel=medium -shared-intel"
CFLAGS="$CFLAGS -mcmodel=medium -shared-intel"
