#!/bin/bash
 
#SBATCH -J runExercise_6
#SBATCH -o runExercise_6.%j.out
#SBATCH -e runExercise_6.%j.err
#SBATCH -N 64
#SBATCH -n 1024
#SBATCH -p normal
#SBATCH -t 00:10:00
#SBATCH --mail-user=timsmith204@utexas.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH -A PCSE-2016

# A useful bash script with a loop for 
# Different core counts and output to unique folders for each

outDir="ex6-output"

if [ ! -d $outDir ] ; then
	mkdir $outDir
fi

numRun=2

while [ $numRun -le $SLURM_NTASKS ]; do
	outName=$(printf '%s/out-%04d.txt' "$outDir" "$numRun")
	ibrun -np $numRun ./6_sort.exe > $outName
	let numRun=numRun*2
done
