#!/bin/bash

#SBATCH -J my_job
#SBATCH -o my_job.%j.out
#SBATCH -e my_job.%j.err
#SBATCH -N 4
#SBATCH -n 96
#SBATCH -p normal
#SBATCH -t 15:00:00

#SBATCH --mail-user=timsmith204@utexas.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

ibrun -np 96 tacc_affinity ./mitgcmuv_ad
