#!/bin/bash

#SBATCH -J rapid 
#SBATCH -o rapid.%j.out
#SBATCH -e rapid.%j.err
#SBATCH -N 6
#SBATCH -n 96
#SBATCH -p sched_mit_hill
#SBATCH -t 12:00:00
#SBATCH --mail-user=timsmith204@utexas.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end


. /etc/profile.d/modules.sh
module add gcc
module add netcdf/gcc
module add mvapich2/gcc

mpiexec -np 96 ./mitgcmuv
