#! /bin/bash

## tmux ftw
#tmux source-file /Users/tim/work/gcm-contrib/bash-scripts/tmux.conf

## Other machines
#alias ekman='mosh --ssh="ssh -p 8704" ekman.ices.utexas.edu'
alias ekman='ssh -p 8704 -J tsmith@login1.ices.utexas.edu tsmith@ekman.ices.utexas.edu'
alias sshek='ssh -p 8704 -J tsmith@login1.ices.utexas.edu tsmith@ekman.ices.utexas.edu'
#alias rsyncek="rsync -ave 'ssh -p 8704'"
alias rsyncek="rsync -ave 'ssh -p 8704 -J tsmith@login1.ices.utexas.edu' --progress" 
#alias scpek="scp -P 8704"
alias scpek="scp  -P 8704 -o 'ProxyJump tsmith@login1.ices.utexas.edu'"
alias amundsen='mosh --ssh"ssh -p 8704" amundsen.ices.utexas.edu'
alias nansen='mosh --ssh"ssh -p 8704" nansen.ices.utexas.edu'

## remote jupyter notebook on ekman ##
alias jupyterek='ssh -p 8704 -J tsmith@login1.ices.utexas.edu -L localhost:8888:localhost:8889 ekman.ices.utexas.edu'
alias jupytersv='ssh -p 8704 -J tsmith@login1.ices.utexas.edu -L localhost:8890:localhost:8889 sverdrup.ices.utexas.edu'

## vnc session command on ekman ##
alias vncek='ssh -p 8704 -J tsmith@login1.ices.utexas.edu -L localhost:5901:localhost:5901 ekman.ices.utexas.edu'

## Directories
export HOME=/Users/tim
export WORK=/Users/tim/work
export contrib=$WORK/gcm-contrib
export computing=$WORK/computing
export write_repo=$WORK/write-repo
export bash_envy=$WORK/bash-envy
export mitgcm=$WORK/MITgcm

## Nonlocal directories
export thamoc=/workspace/gcm-contrib/samoc

## Path and LD_LIBRARY
export PATH=$PATH:/Library/TeX/Distributions/Programs/texbin

### For MITgcm ###
export CVSROOT=':pserver:cvsanon@mitgcm.org:/u/gcmpack'
export CVSEDITOR=vim

## Commands
export PS1='[tim \W]\$ '
alias o='open'

### Refresh tmux environment variables ###
. $bash_envy/env/refresh_tmux_env

### Refresh mac display specifically
export DISPLAY=':0'

### Colorize grep output unless being piped to file ###
export GREP_OPTIONS='--color=auto'
