#!/bin/bash

## Modules 
module load comp-intel
module load mpi-sgi/mpt
module load hdf4 hdf5 netcdf

## Useful Directories
export WORK=/nobackupp2/tasmit12
export contrib=$WORK/gcm-contrib
export computing=$WORK/computing
# Directory containing full ERA-Interim dataset, 1979-2014
export ph_work=/nobackupp8/pheimbac
export era_interim=/nobackupp8/pheimbac/data/ecmwf-interim-bulk
export mitgcm=~/MITgcm_c66i+
export bash-envy=$WORK/bash-envy

## Commands
alias qu='qstat -u tasmit12'
export PS1='[\h \W]\$ '
