#!/bin/bash 

### Environment Variables ###
#############################
PATH=$HOME/.local/bin:$PATH

### Directories ###
###################
export TERM=xterm-256color
export WORK=/workspace/tsmith
export data=/mnt/data/tsmith
export contrib=$WORK/gcm-contrib
export sv=$WORK/sv-mnt
export computing=$WORK/computing
export mitgcm=$WORK/MITgcm
export bash_envy=$WORK/bash-envy
export pig=$WORK/ase-adjoint/pig/generic
export ase=$WORK/ase-adjoint


### Add python packages from GitHub ###
if [ -z $PYTHONPATH ] || [[ $PYTHONPATH != *"xmitgcm"* ]] ; then
    export PYTHONPATH=$PYTHONPATH:$WORK/xgcm
    export PYTHONPATH=$PYTHONPATH:$WORK/xmitgcm
    export PYTHONPATH=$PYTHONPATH:$WORK/ECCOv4-py
    export PYTHONPATH=$PYTHONPATH:$WORK/pych
    export PYTHONPATH=$PYTHONPATH:$WORK/rosy-pig
    export PYTHONPATH=$PYTHONPATH:$WORK/xmovie
    export PYTHONPATH=$PYTHONPATH:$mitgcm/utils/python/MITgcmutils
fi

### Aliases
alias cds='cd $sv'
alias cdp='cd $pig'
alias cdm='cd $mitgcm'
alias cda='cd $ase'
alias o='&>/dev/null kde-open5'

alias lpq3='lpq -P cp3se'
alias lp='lp -o fit-to-page -o sides=two-sided-long-edge'

### Link to Sverdrup ###
alias sv-sshfs="sshfs -o IdentityFile=~/.ssh/id_rsa sverdrup.oden.utexas.edu:/home/tsmith /workspace/tsmith/sv-mnt"

### Modules ###
module load ubt18 intel

### Parallel Algorithms Class stuff ###
export pcse_repo='https://bitbucket.org/VictorEijkhout/pcse2016'

### Increase stack size ###
ulimit -s hard
ulimit -u hard

### Refresh tmux environment variables ###
. $bash_envy/env/refresh_tmux_env

### Refresh display environment variable if not in vnc session
### If in VNC session, then don't add anaconda to path because
### the qt binaries in anaconda3/bin mess up startkde...
if [ `xdpyinfo -display :1 | grep -c VNC` == 0 ] ; then
    export DISPLAY=':1'

# added by Anaconda3 5.3.0 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
    __conda_setup="$(CONDA_REPORT_ERRORS=false '/workspace/tsmith/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
    if [ $? -eq 0 ]; then
        \eval "$__conda_setup"
    else
        if [ -f "/anaconda3/tsmith/etc/profile.d/conda.sh" ]; then
            . "/workspace/tsmith/anaconda3/etc/profile.d/conda.sh"
            CONDA_CHANGEPS1=false conda activate base
    
        else
            \export PATH="/workspace/tsmith/anaconda3/bin:$PATH"
        fi
    fi
    unset __conda_setup
# <<< conda init <<<
fi

### Reset PS1 after conda messes with it ...
export PS1='[\h \W]\$ '

### Expand environment variables in tab completion ###
shopt -s direxpand
