#! /bin/bash

### Change prompt ###
export PS1='[corral \W]\$ '

### Directories ###
export WORK=/corral-repl/utexas/Transfer-of-ECCO-glo
export corral_storage=/corral-repl/utexas/Transfer-of-ECCO-glo
export bash_envy=~/bash-envy

### Expand environment variables in tab completion ###
shopt -s direxpand
