#! /bin/bash

### Remote servers ###
######################
. $bash_envy/env/remote_aliases

### Ekman ###
#############
alias ekman='ssh -p 8704 -J tsmith@login1.ices.utexas.edu tsmith@ekman.ices.utexas.edu'
alias jupyterek='ssh -p 8704 -J tsmith@login1.ices.utexas.edu -L localhost:8889:localhost:8889 ekman.ices.utexas.edu'
alias vncek='ssh -p 8704 -J tsmith@login1.ices.utexas.edu -L localhost:5901:localhost:5901 ekman.ices.utexas.edu'

alias rsyncek="rsync -ave 'ssh -p 8704 -J tsmith@login1.ices.utexas.edu' --progress" 
alias scpek="scp  -P 8704 -o 'ProxyJump tsmith@login1.ices.utexas.edu'"

export thamoc=/workspace/gcm-contrib/samoc

### Jupyter notebooks ###
#########################
alias jupyterek='ssh -p 8704 -J tsmith@login1.ices.utexas.edu -L localhost:8889:localhost:8889 ekman.ices.utexas.edu'

# For compute node notebook, need to pass IP address
#   1. Create a temporary function which takes in passed arguments
#   2. unset the temp function after running the desired ssh command
#   3. execute
alias jupytersv='temporary_function(){
    ssh -p 8704 -i ~/.ssh/sverdrup_rsa -J tsmith@login1.ices.utexas.edu -L localhost:8890:"$@":8890 sverdrup.ices.utexas.edu; 
    unset -f temporary_function;}; 
    temporary_function'

### Directories ###
###################
export HOME=/Users/tim
export WORK=/Users/tim/work
export contrib=$WORK/gcm-contrib
export computing=$WORK/computing
export write_repo=$WORK/write-repo
export bash_envy=$WORK/bash-envy
export mitgcm=$WORK/MITgcm

## Path and LD_LIBRARY
export PATH=$PATH:/Library/TeX/Distributions/Programs/texbin

### For MITgcm ###
export CVSROOT=':pserver:cvsanon@mitgcm.org:/u/gcmpack'
export CVSEDITOR=vim

### Refresh tmux environment variables ###
. $bash_envy/env/refresh_tmux_env

### Refresh mac display specifically
export DISPLAY=':0'

### Colorize grep output unless being piped to file ###
export GREP_OPTIONS='--color=auto'

### Conda 
source activate base
conda deactivate
conda activate base

## Commands
export PS1='[tim \W]\$ '
alias o='open'
