#!/bin/bash 

## set terminal
export TERM=xterm-256color

## Modules
#module load c7 # not available
module load intel
module load openmpi
module load netcdf-fortran

## Directories
export HOME=/home/tsmith
export SCRATCH=/scratch/tsmith
export contrib=/home/tsmith/gcm-contrib
export computing=/home/tsmith/computing
export MPI_INC_DIR=$MPI_DIR/include
export ph_data=/scratch/heimbach/data
export ase=/scratch/tsmith/MITgcm/ase-adjoint
export pig=/scratch/tsmith/MITgcm/ase-adjoint/pig/generic
export mitgcm=~/MITgcm
export bash_envy=~/bash-envy

## Commands
export PS1='[\h \W]\$ '
alias scpthorne='scp -P 8704'
alias qu='squeue -u tsmith'
alias cda='cd $ase'
alias cdp='cd $pig'

## Increase stack size
ulimit -s hard
ulimit -u hard

### Expand environment variables in tab completion ###
shopt -s direxpand
