#!/bin/bash


if [[ "$HOSTNAME" == "login"* ]] ; then

  . /work/03754/tsmith/bash-envy/env/bashrc_tacc

elif [[ "$HOSTNAME" == "pfe"* ]] ; then

  . /nobackupp2/tasmit12/bash-envy/env/bashrc_pfe

elif [[ "$HOSTNAME" == "sverdrup"* ]] ; then

  . /home/tsmith/bash-envy/env/bashrc_sverdrup

elif [[ "$HOSTNAME" == "ekman"* ]] ; then

  source /workspace/bash-envy/env/bashrc_ekman

elif [ "$USER" == "tim" ] ; then

  . /Users/tim/work/bash-envy/env/bashrc_mac

elif [[ "$HOSTNAME" == *"corral"* ]] ; then 
  
  . ~/bash-envy/env/bashrc_corral

elif [[ "$USER" == "u00u6fuc3j0gv1XhWq357" ]] ; then

  . $HOME/bash-envy/env/bashrc_nvidia

elif [[ "$HOSTNAME" == "mac76" ]] ; then

  . $HOME/work/bash-envy/env/bashrc_noaamac

fi

# -------------------------------------------------------------
# All machines
# -------------------------------------------------------------

if [[ "$HOSTNAME" != "mac76" ]] ; then
  ### Add local bin/lib to path ### 
  export PATH=$HOME/local/bin:$PATH
  export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH:
  export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
  
  ### CVS Stuff ###
  export CVSROOT=':pserver:cvsanon@mitgcm.org:/u/gcmpack'
  export CVSEDITOR=vim

  alias cdc='cd $contrib'
  alias cdm='cd $mitgcm'

  if [[ "$HOSTNAME" != "ekman"* ]] ; then
    alias cds='cd $SCRATCH'
  fi
fi

## Misc commands and specs ##
alias cdh='cd $HOME'
alias cdw='cd $WORK'
alias cdb='cd $bash_envy'

if [ "$USER" != "tim" ] && [ "$HOSTNAME" != "mac76" ] ; then
    alias ls='ls --color=auto' 
else
    alias ls='ls -G'
fi
alias ll='ls -alh'
