#! /bin/zsh

### Clear path before path_helper runs ###
# see https://superuser.com/questions/544989/does-tmux-sort-the-path-variable/583502#583502
if [ -f /etc/profile ]; then
    PATH=""
    source /etc/profile
fi

# Ignore zsh message
export BASH_SILENCE_DEPRECATION_WARNING=1

## git bash completion
# would be nice to have this installed, not sure what the dbus
# completion is, leaving it here for future reference
#source /opt/local/etc/bash_completion.d/dbus-bash-completion.sh

# The latex installation from MacPorts is messed up
# this brings TexBin back to the front
export PATH=/Library/TeX/texbin:$PATH
export PATH=$PATH:/Users/tsmith/.local/bin

### Directories ###
###################
export HOME=/Users/tsmith
export WORK=/Users/tsmith/work
export bash_envy=$WORK/bash-envy

### Refresh tmux environment variables ###
. $bash_envy/env/refresh_tmux_env

### Refresh mac display specifically
export DISPLAY=':0'

### Colorize grep output unless being piped to file ###
export GREP_OPTIONS='--color=auto'

## Commands
export PS1='[tim \W]$ '
alias o='open'

# --- GCP Parallel works
export CLOUDSDK_CORE_PROJECT=noaa-users
export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=$HOME/project-key.json

function findreplace() {
    if [ "$#" -ne 2 ]; then
        echo "Usage: findreplace <search_term> <replace_term>"
        return 1
    fi

    echo "Replacing '$1' with '$2' in all files..."

    # Removed the .git exclusion. The LC_ALL=C fix remains to prevent byte errors.
    find . -type f -exec env LC_ALL=C sed -i '' "s|$1|$2|g" {} +

    echo "Done."
}


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/tsmith/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/tsmith/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/tsmith/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/tsmith/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
