#! /bin/bash

### Clear path before path_helper runs ###
# see https://superuser.com/questions/544989/does-tmux-sort-the-path-variable/583502#583502
#if [ -f /etc/profile ]; then
#    PATH=""
#    source /etc/profile
#fi

# Ignore zsh message
export BASH_SILENCE_DEPRECATION_WARNING=1

### Directories ###
###################
export WORK=/Users/tsmith/work
export data=/Users/tsmith/data
export bash_envy=$WORK/bash-envy

## Python
add_python_package "ddhf" "$WORK/ddhf"
add_python_package "data-driven-collab" "$WORK/data-driven-collab"
add_python_package "mlcdc" "$WORK/mlcdc"

## Path and LD_LIBRARY
export PATH=/Library/TeX/Distributions/Programs/texbin:$PATH
export PATH=/opt/anaconda3/bin:$PATH

### Colorize grep output unless being piped to file ###
export GREP_OPTIONS='--color=auto'

## Commands
export PS1='[noaa \W]\$ '

# --- GCP Parallel works
export CLOUDSDK_CORE_PROJECT=noaa-users
export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=$HOME/.gcp/project-key.json
