#! /bin/bash

## Directories
export WORK=/contrib/Tim.Smith
export bash_envy=$WORK/bash-envy
export container=$WORK/containers/ddc_pw_cpu_latest.sif

## Python
if [ -z $PYTHONPATH ] || [[ $PYTHONPATH != *"pych"* ]] ; then
    export PYTHONPATH=$PYTHONPATH:$WORK/ddhf
    export PYTHONPATH=$PYTHONPATH:$WORK/data-driven-collab
fi

## Commands

alias interactive="srun --nodes=1 --ntasks=2 --cpus-per-task=15 --time=01:00:00  --pty /bin/bash" 
alias qu="squeue -u Tim.Smith"
alias add_github_key="eval '$(ssh-agent -s) ssh-add /contrib/Tim.Smith/.ssh/id_rsa'"

## Modules
#module load intel/20.0.2

if [[ -z $SLURM_JOB_ID ]] ; then
    export PS1='[$nickname \W]\$ '
else
    export PS1='[slurm$SLURM_JOB_ID \W]\$ '
fi
