#! /bin/bash

## Directories
export WORK=/home/tsmith/work
export data=/home/tsmith/data
export bash_envy=$WORK/bash-envy

## Python
if [ -z $PYTHONPATH ] || [[ $PYTHONPATH != *"pych"* ]] ; then
    export PYTHONPATH=$PYTHONPATH:$WORK/ddhf
    export PYTHONPATH=$PYTHONPATH:$WORK/data-driven-collab
fi

## Add tmux to path and libraries from miniconda environment
export PATH=$PATH:$HOME/tmux
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/miniconda3/envs/ddc/lib


## Commands
export PS1='[$nickname \W]\$ '


## Modules
module load intel/20.0.2


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/tsmith/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/tsmith/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/tsmith/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/tsmith/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
