#! /bin/bash

## Directories
export WORK=/pscratch/sd/t/timothys
export COMMON=/global/common/software/m4718/timothys
export COMMUNITY=/global/cfs/cdirs/m4718/timothys
export bash_envy=$HOME/bash-envy
export graphufs=$COMMON/graphufs
export gnugraphufs=$COMMON/gnugraphufs


module load conda/Miniforge3-24.11.3-0
#module load PrgEnv-nvidia cray-mpich cudatoolkit craype-accel-nvidia80 cudnn/8.9.3 nccl/2.21.5

## Azure credentials
source ~/.azure.sh

alias grep="grep --color"

## Commands
alias cdc="cd $COMMON"
alias cdu="cd $COMMUNITY"
alias qu="squeue -u timothys"
alias add_github_key="eval '$(ssh-agent -s) ssh-add $HOME/.ssh/github_ed25519'"
alias interactive_gpu="salloc --nodes 1 --tasks-per-node 4 --gpus-per-node 4 --qos interactive --time 01:00:00 --constraint gpu --account m4718"
alias interactive_gpu80="salloc --nodes 1 --tasks-per-node 4 --gpus-per-node 4 --qos interactive --time 01:00:00 --constraint 'gpu&hbm80g' --account m4718"
alias interactive_cpu64="salloc --nodes 1 --tasks-per-node 64 --cpus-per-task 4 --qos interactive --time 01:00:00 --constraint cpu --account m4718"
alias interactive_cpu32="salloc --nodes 1 --tasks-per-node 32 --cpus-per-task 8 --qos interactive --time 01:00:00 --constraint cpu --account m4718"
alias interactive_cpu="salloc --nodes 1 --tasks-per-node 64 --cpus-per-task 4 --qos interactive --time 01:00:00 --constraint cpu --account m4718"
alias interactive_cpu128="salloc --nodes 1 --tasks-per-node 128 --cpus-per-task 2 --qos interactive --time 01:00:00 --constraint cpu --account m4718"
alias interactive_cpu16="salloc --nodes 1 --tasks-per-node 16 --cpus-per-task 16 --qos interactive --time 01:00:00 --constraint cpu --account m4718"
alias interactive_cpu_notasks="salloc --nodes 1 --exclusive --qos interactive --time 01:00:00 --constraint cpu --account m4718"

# Command to figure out how long a slurm job took
stime() {
    # Check if a Job ID was provided
    if [ -z "$1" ]; then
        echo "Error: No Job ID provided."
        echo "Usage: stime <jobid>"
        return 1
    fi

    # Run the sacct command with the requested formatting
    sacct -j "$1" --format=JobID,JobName,State,Elapsed,Start,End
}

function findreplace() {
    if [ "$#" -ne 2 ]; then
        echo "Usage: findreplace <search_term> <replace_term>"
        return 1
    fi

    echo "Replacing '$1' with '$2' in all files..."
    find . -type f -exec sed -i "s|$1|$2|g" {} +
    echo "Done."
}

if [[ -z $SLURM_JOB_ID ]] ; then
    export PS1='[$nickname \W]\$ '
    eval $(ssh-agent -s)
    ssh-add ~/.ssh/github_ed25519
else
    export PS1='[slurm$SLURM_JOB_ID \W]\$ '
fi

### Expand environment variables in tab completion ###
shopt -s direxpand
