#!/bin/bash



# Directories
export bash_envy=$HOME/bash-envy
export ddc=$HOME/data-driven-collab
export hddc=/home/noaa_data-driven-collab
export PYTHONPATH=$PYTHONPATH:$HOME/data-driven-collab

export PS1='[\[\033[01;32m\]\h\[\033[00m\] \[\033[01;34m\]\W\[\033[00m\]]\$ '


# Aliases
alias qu='squeue -u u00u6fuc3j0gv1XhWq357'
alias cdd='cd $ddc'

### Refresh tmux environment variables ###
. $bash_envy/env/refresh_tmux_env
