#! /bin/bash

### Clear path before path_helper runs ###
# see https://superuser.com/questions/544989/does-tmux-sort-the-path-variable/583502#583502
if [ -f /etc/profile ]; then
    PATH=""
    source /etc/profile
fi

# Ignore zsh message
export BASH_SILENCE_DEPRECATION_WARNING=1

# git bash completion
source /usr/local/etc/bash_completion.d/git-completion.bash

# for brew installed tmux ... next time from source
export PATH=/usr/local/opt/bin:$PATH
export PATH=/usr/local/opt/ruby/bin:$PATH

### Directories ###
###################
export HOME=/Users/tim
export WORK=/Users/tim/work
export contrib=$WORK/gcm-contrib
export computing=$WORK/computing
export write_repo=$WORK/write-repo
export bash_envy=$WORK/bash-envy
export mitgcm=$WORK/MITgcm

### Add python packages from GitHub ###
if [ -z $PYTHONPATH ] || [[ $PYTHONPATH != *"xmitgcm"* ]] ; then
    export PYTHONPATH=$PYTHONPATH:$WORK/xgcm
    export PYTHONPATH=$PYTHONPATH:$WORK/xmitgcm
    export PYTHONPATH=$PYTHONPATH:$WORK/ECCOv4-py
    export PYTHONPATH=$PYTHONPATH:$WORK/pych
    export PYTHONPATH=$PYTHONPATH:$WORK/rosy-pig
    export PYTHONPATH=$PYTHONPATH:$WORK/xmovie
    export PYTHONPATH=$PYTHONPATH:$mitgcm/utils/python/MITgcmutils
    export PYTHONPATH=$PYTHONPATH:$WORK/data-driven-collab
    export PYTHONPATH=$PYTHONPATH:$WORK/ddhf
fi

### Ekman ###
#############
alias ekman='ssh -J tsmith@login1.oden.utexas.edu tsmith@ekman.oden.utexas.edu'
alias jupyterek='ssh -J tsmith@login1.oden.utexas.edu -L localhost:8889:localhost:8889 ekman.oden.utexas.edu'
alias vncek='ssh -J tsmith@login1.oden.utexas.edu -L localhost:5901:localhost:5901 ekman.oden.utexas.edu'

alias rsyncek="rsync -ave 'ssh -p 8704 -J tsmith@login1.oden.utexas.edu' --progress" 
alias scpek="scp -o 'ProxyJump tsmith@login1.oden.utexas.edu'"

export thamoc=/workspace/gcm-contrib/samoc


## Path and LD_LIBRARY
export PATH=$PATH:/Library/TeX/Distributions/Programs/texbin

### For MITgcm ###
export CVSROOT=':pserver:cvsanon@mitgcm.org:/u/gcmpack'
export CVSEDITOR=vim

### Refresh tmux environment variables ###
. $bash_envy/env/refresh_tmux_env

### Refresh mac display specifically
export DISPLAY=':0'

### Colorize grep output unless being piped to file ###
export GREP_OPTIONS='--color=auto'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/tim/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/tim/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/tim/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/tim/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


## Commands
export PS1='[tim \W]\$ '
alias o='open'
