#! /bin/bash

### Directories ###
###################
export WORK=/home/tsmith/work
export data=/home/tsmith/data
export bash_envy=$WORK/bash-envy

## Python
add_python_package "ddhf" "$WORK/ddhf"
add_python_package "xesn" "$WORK/xesn"
add_python_package "ufs2arco" "$WORK/ufs2arco"
add_python_package "graphcast" "$WORK/graphcast"

## Add tmux to path
export PATH=$PATH:$WORK/tmux

## Commands
export PS1='[$nickname \W]\$ '
