#!/bin/bash


if [[ "$HOSTNAME" == "login"* ]] ; then

  . /work/03754/tsmith/bash-envy/env/bashrc_tacc

elif [[ "$HOSTNAME" == "pfe"* ]] ; then

  . /nobackupp2/tasmit12/bash-envy/env/bashrc_pfe

elif [[ "$HOSTNAME" == "sverdrup"* ]] ; then

  . /home/tsmith/bash-envy/env/bashrc_sverdrup

elif [[ "$HOSTNAME" == "ekman"* ]] ; then

  source /workspace/bash-envy/env/bashrc_ekman

elif [ "$USER" == "tim" ] ; then

  . /Users/tim/work/bash-envy/env/bashrc_mac

elif [[ "$HOSTNAME" == *"corral"* ]] ; then 
  
  . ~/bash-envy/env/bashrc_corral

fi

# -------------------------------------------------------------
# All machines
# -------------------------------------------------------------

### Add local bin/lib to path ### 
export PATH=$PATH:$HOME/local/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib

### Add python modules ###
# Note: for now, on mac and Ekman they are just in $WORK
if [[ "$HOSTNAME" == "sverdrup"* ]] ; then
    export PYTHONPATH=$PYTHONPATH:$HOME/xgcm:$HOME/xmitgcm:$HOME/MITgcm-recipes
    export PYTHONPATH=$PYTHONPATH:$HOME/pych
    export PYTHONPATH=$PYTHONPATH:$HOME/ECCOv4-py
    export PYTHONPATH=$PYTHONPATH:$HOME/ECCOv4-py/ecco_v4_py
    export PYTHONPATH=$PYTHONPATH:$HOME/xecco
elif [[ "$HOSTNAME" == "login"* ]] ; then
    export PYTHONPATH=$PYTHONPATH:$WORK/../xgcm:$WORK/../xmitgcm
    export PYTHONPATH=$PYTHONPATH:$WORK/../ECCOv4-py:$WORK/../ECCOv4-py/ecco_v4_py
    export PYTHONPATH=$PYTHONPATH:$WORK/../xecco
    export PYTHONPATH=$PYTHONPATH:$WORK/../pych
else
    export PYTHONPATH=$PYTHONPATH:$WORK/xgcm:$WORK/xmitgcm
    export PYTHONPATH=$PYTHONPATH:$WORK/ECCOv4-py:$WORK/ECCOv4-py/ecco_v4_py
    export PYTHONPATH=$PYTHONPATH:$WORK/xecco
    export PYTHONPATH=$PYTHONPATH:$WORK/pych
fi
export PYTHONPATH=$PYTHONPATH:$mitgcm/utils/python/MITgcmutils

### CVS Stuff ###
export CVSROOT=':pserver:cvsanon@mitgcm.org:/u/gcmpack'
export CVSEDITOR=vim

## Misc commands and specs ##
alias cdh='cd $HOME'
alias cdw='cd $WORK'
alias cdc='cd $contrib'
alias cdm='cd $mitgcm'
if [[ "$HOSTNAME" != "ekman"* ]] ; then
  alias cds='cd $SCRATCH'
fi
alias cdb='cd $bash_envy'

if [ "$USER" != "tim" ] ; then
    alias ls='ls --color=auto' 
else
    alias ls='ls -G'
fi
alias ll='ls -alh'
