#!/bin/bash 

### Environment Variables ###
PATH=/h2/tsmith/.local/bin:$PATH
export TERM=xterm-256color
export WORK=/workspace
export data=/mnt/data
export contrib=/workspace/gcm-contrib
export sv=/workspace/sv-mnt
export computing=/workspace/computing
export mitgcm=/workspace/MITgcm
export bash_envy=/workspace/bash-envy
export pig='/workspace/ase-adjoint/pig/generic'
export ase='/workspace/ase-adjoint'

### Aliases
alias cds='cd $sv'
alias cdp='cd $pig'
alias cdm='cd $mitgcm'
alias cda='cd $ase'
alias o='&>/dev/null kde-open '
export PS1='[\h \W]\$ '
alias lpq3='lpq -P cp3se'
alias lp='lp -o fit-to-page -o sides=two-sided-long-edge'

### SSH Ports ###
# big guys
alias pfe='ssh pfe'
alias stampede='ssh -i ~/.ssh/stampede2_rsa tsmith@login2.stampede2.tacc.utexas.edu'
alias lonestar='mosh login2.ls5.tacc.utexas.edu'
alias corral='ssh data.tacc.utexas.edu'

# local machines
alias sverdrup='mosh --ssh="ssh -p 8704" sverdrup.ices.utexas.edu'
alias scpsv='scp -P 8704'
alias arctowski='mosh --ssh"ssh -p 8704" arctowski'
alias amundsen='mosh --ssh"ssh -p 8704" amundsen'
alias nansen='mosh --ssh"ssh -p 8704" nansen'

# Don't really use these anymore
alias glacier='mosh timothys@glacier0.mit.edu'
alias engaging4='mosh --ssh="ssh -i ~/.ssh/id_rsa_eofe-mit" timothys@eofe4.mit.edu'
alias engaging='mosh --ssh="ssh -i ~/.ssh/id_rsa_eofe-mit" timothys@eofe5.mit.edu'
alias scpengaging='scp -i ~/.ssh/id_rsa_eofe-mit'

### Link to Sverdrup ###
alias sv-sshfs="sshfs -p 8704 -o IdentityFile=~/.ssh/id_rsa sverdrup.ices.utexas.edu:/home/tsmith /workspace/sv-mnt"

### Modules ###
module purge
module load c7 intel/17.0 mpich/3.0.4 matlab texlive

### Parallel Algorithms Class stuff ###
export pcse_repo='https://bitbucket.org/VictorEijkhout/pcse2016'

### Directories for servers
export pfework='/nobackupp2/tasmit12'
export lswork='/work/03754/tsmith/lonestar'
export stampwork='/work/03754/tsmith/stampede2'
export eofework='/nobackup1/timothys'
export svwork='/scratch/tsmith'
export svpig='/scratch/tsmith/MITgcm/ase-adjoint/pig/generic'
export corral_dir='/corral-repl/utexas/Transfer-of-ECCO-glo/tsmith'


### Increase stack size ###
ulimit -s hard
ulimit -u hard

### Refresh tmux environment variables ###
. $bash_envy/env/refresh_tmux_env

### Refresh display environment variable if not in vnc session
if [ `xdpyinfo | grep -c VNC` == 0 ] ; then
    export DISPLAY=':0'
fi

### Expand environment variables in tab completion ###
shopt -s direxpand
