#! /bin/bash

## Directories
export WORK=/contrib2/Tim.Smith
export bash_envy=$WORK/bash-envy

## Python
add_python_package "graphufs" "$WORK/graph-ufs"
add_python_package "graphcast" "$WORK/graph-ufs/graphcast"
add_python_package "ufs2arco" "$WORK/graph-ufs/ufs2arco"


## Commands
alias interactive_cpu48="srun --nodes=1 --ntasks=1 --partition=cpuD48v5 --cpus-per-task=48 --time=09:00:00  --pty /bin/bash"
alias interactive_cpu32="srun --nodes=1 --ntasks=1 --partition=cpuD32v5 --cpus-per-task=32 --time=09:00:00  --pty /bin/bash"
alias interactive_gpu="srun --nodes=1 --ntasks=1 --partition=gpu --cpus-per-task=24 --time=09:00:00  --pty /bin/bash"
alias interactive_gpu2="srun --nodes=1 --ntasks=1 --partition=gpu2 --cpus-per-task=48 --time=09:00:00  --pty /bin/bash"
alias interactive_gpu4="srun --nodes=1 --ntasks=1 --partition=gpu4 --cpus-per-task=96 --time=09:00:00  --pty /bin/bash"
alias qu="squeue -u Tim.Smith"
alias add_github_key="eval '$(ssh-agent -s) ssh-add /contrib2/Tim.Smith/.ssh/id_ed25519'"

if [[ -z $SLURM_JOB_ID ]] ; then
    export PS1='[$nickname \W]\$ '
else
    export PS1='[slurm$SLURM_JOB_ID \W]\$ '
fi


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/contrib2/Tim.Smith/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/contrib2/Tim.Smith/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/contrib2/Tim.Smith/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/contrib2/Tim.Smith/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Expand environment variables in tab complete
shopt -s direxpand
