#!/bin/bash
#
# --- Add key created in contrib to ssh-agent to use git
eval $(ssh-agent)

if [[ "$PW_CSP" == "gcp" || "$PW_CSP" == "google" ]] ; then
    ssh-add /contrib/Tim.Smith/.ssh/id_ed25519
elif [[ "$PW_CSP" == "aws" ]] ; then
    ssh-add /contrib/Tim.Smith/.ssh/id_rsa
elif [[ "$PW_CSP" == "azure" ]] ; then
    ssh-add /contrib2/Tim.Smith/.ssh/id_ed25519
fi
