#!/bin/bash


# Define jump option for ssh to Oden from MAC
if [[ "$nickname" == "home" ]] ; then
    # On mac
    export ssh_jump='-J tsmith@login1.oden.utexas.edu'
    export scp_jump="-o 'ProxyJump tsmith@login1.oden.utexas.edu'"
else
    export ssh_jump=''
    export scp_jump=''
fi


### SSH ###
###########

# Oden
alias sverdrup='ssh -p 8704 -i ~/.ssh/sverdrup_rsa '$ssh_jump' tsmith@sverdrup.oden.utexas.edu'
alias amundsen='ssh -p 8704 '$ssh_jump' tsmith@amundsen.oden.utexas.edu'
alias nansen='ssh -p 8704 '$ssh_jump' tsmith@nansen.oden.utexas.edu'

# NASA
alias pfe='ssh pfe'

# TACC
alias frontera='ssh -i ~/.ssh/frontera_rsa tsmith@login2.frontera.tacc.utexas.edu'
alias stampede='ssh -i ~/.ssh/stampede2_rsa tsmith@login2.stampede2.tacc.utexas.edu'
alias lonestar='ssh -i ~/.ssh/ls5_rsa tsmith@login2.ls5.tacc.utexas.edu'
alias corral='ssh -i ~/.ssh/corral_rsa tsmith@data.tacc.utexas.edu'

# MIT
alias glacier='mosh timothys@glacier0.mit.edu'
alias engaging4='mosh --ssh="ssh -i ~/.ssh/id_rsa_eofe-mit" timothys@eofe4.mit.edu'
alias engaging='mosh --ssh="ssh -i ~/.ssh/id_rsa_eofe-mit" timothys@eofe5.mit.edu'


### SCP ###
###########

# Oden
alias scpsv="scp -P 8704 "$scp_jump" -i ~/.ssh/sverdrup_rsa"

# TACC
alias scpfrontera='scp -i ~/.ssh/frontera_rsa'
alias scpstampede2='scp -i ~/.ssh/stampede2_rsa'
alias scplonestar='scp -i ~/.ssh/ls5_rsa'
alias scpcorral='scp -i ~/.ssh/corral_rsa'

# MIT
alias scpengaging='scp -i ~/.ssh/id_rsa_eofe-mit'

### Jupyter notebooks ###
#########################
# For compute node notebook, need to pass port number and IP address
jupytersv () {
    ssh -p 8704 -i ~/.ssh/sverdrup_rsa $ssh_jump -L localhost:$1:$2:$1 sverdrup.oden.utexas.edu; 
}


### Directories ###
###################

# Sverdrup
export svwork='/scratch/tsmith'
export svpig='/scratch/tsmith/MITgcm/ase-adjoint/pig/generic'

# NASA
export pfework='/nobackupp2/tasmit12'

# TACC
export lswork='/work/03754/tsmith/lonestar'
export stampwork='/work/03754/tsmith/stampede2'
export fronterawork='/work/03754/tsmith/frontera'
export taccwork='/work/03754/tsmith'
export taccscratch='/scratch/03754/tsmith'
export fronterascratch='/scratch1/03754/tsmith'
export corral_dir='/corral-repl/utexas/Transfer-of-ECCO-glo/tsmith'

# MIT
export eofework='/nobackup1/timothys'
