#!/bin/bash

if [[ "$nickname" == "home" ]] ; then
    export psl_mac_sshfile=~/.ssh/mac76_rsa

elif [[ "$nickname" == "noaa_home" ]] ; then
    export psl_mac_sshfile=~/.ssh/mac76_ed25519
    export psl_linux_sshfile=~/.ssh/psl_linux_rsa
    export apollo_sshfile=~/.ssh/apollo_ed25519
    export hera_sshfile=~/.ssh/hera_rsa
    export orion_sshfile=~/.ssh/orion_ecdsa
    export pw_sshfile=~/.ssh/pw_parallel_works_rsa
elif [[ "$nickname" == "noaa_psl" ]] ; then
    export pw_sshfile=~/.ssh/pw_parallel_works_rsa
    export hera_sshfile=~/.ssh/psl_hera_rsa
fi

### SSH ###
###########

# NOAA
alias noaamac="ssh -i ${psl_mac_sshfile} tsmith@mac20.psd.esrl.noaa.gov"

# Hera
alias hera="ssh -i ${hera_sshfile} -XL 2169:localhost:2169 Tim.Smith@hera-rsa.boulder.rdhpcs.noaa.gov"

# linux twins
alias linux1024="ssh tsmith@linux1024.psd.esrl.noaa.gov"
alias linux512="ssh tsmith@linux512.psd.esrl.noaa.gov"

# apollo
alias apollo="ssh -i ${apollo_sshfile} tsmith@apollo1-headnode2.psd.esrl.noaa.gov"

# orion
alias orion="ssh -i ${orion_sshfile} tsmith@orion-login.hpc.msstate.edu"

# PW
alias sshpw="ssh -i ${pw_sshfile}"


### SCP ###
###########

# send out
scp-to-psl(){
    scp -i ${psl_mac_sshfile} $1 tsmith@mac20.psd.esrl.noaa.gov:$2
}

scp-to-apollo(){
    scp -i ${apollo_sshfile} $1 tsmith@apollo1-headnode2.psd.esrl.noaa.gov:$2
}

scp-to-hera(){
    scp -i ${hera_sshfile} $1 Tim.Smith@dtn-hera.fairmont.rdhpcs.noaa.gov:$2
}
scp-to-pw(){
    scp -i ${pw_sshfile} $1 $2:$3
}

# send here
scp-from-psl(){
    scp -i ${psl_mac_sshfile} tsmith@mac20.psd.esrl.noaa.gov:$1 $2
}

scp-from-apollo(){
    scp -i ${apollo_sshfile} tsmith@apollo1-headnode2.psd.esrl.noaa.gov:$1 $2
}

scp-from-hera(){
    scp -i ${hera_sshfile} Tim.Smith@dtn-hera.fairmont.rdhpcs.noaa.gov:$1 $2
}

scp-from-pw(){
    scp -i ${pw_sshfile} $1:$2 $3
}



### Jupyter notebooks ###
#########################
alias noaanote="ssh -i ${psl_mac_sshfile} -L localhost:8899:localhost:8899 tsmith@mac20.psd.esrl.noaa.gov"
alias linuxnote="ssh -L localhost:8890:localhost:8890 tsmith@linux1024.psd.esrl.noaa.gov"

noaaport (){
    ssh -i ${psl_mac_sshfile} -L localhost:$1:localhost:$2 tsmith@mac20.psd.esrl.noaa.gov
}

linuxport (){
    ssh -L localhost:$1:localhost:$2 tsmith@linux1024.psd.esrl.noaa.gov
}

apolloport (){
    ssh -i ${apollo_sshfile} -L localhost:$1:192.168.1.$2:$3 tsmith@apollo1-headnode2.psd.esrl.noaa.gov
}

heraport (){
    ssh -i ${hera_sshfile} -p 2169 -L $1:$2:$3 Tim.Smith@localhost
}

pwport (){
    ssh -i ${pw_sshfile} $1":localhost:"$1 $2
}


### Directories ###
###################
export apollo_work='/home/tsmith/work/'
export apollo_ddc=$apollo_work/data-driven-collab
