#! /bin/bash

# --- Add key created in contrib to ssh-agent to use git
eval $(ssh-agent)
ssh-add /contrib/Tim.Smith/.ssh/id_rsa

# --- Add basic environment stuff
echo "source /contrib/Tim.Smith/bash-envy/env/bashrc_master" >> ~/.bashrc
echo "source /contrib/Tim.Smith/bash-envy/env/vimrc" >> ~/.vimrc
echo "source-file /contrib/Tim.Smith/bash-envy/env/tmux.conf" >> ~/.tmux.conf
source ~/.bashrc

# --- Some git config
git config --global user.name "timothyas"
git config --global user.email "timsmith204@utexas.edu"
git config --global color.ui true
git config --global push.default simple

# --- Dask configuring
mkdir -p ~/.config/dask
cp /contrib/Tim.Smith/ddhf/pw/distributed.yaml ~/.config/dask/distributed.yaml
cp /contrib/Tim.Smith/ddhf/pw/dask.yaml ~/.config/dask/dask.yaml
cp /contrib/Tim.Smith/ddhf/pw/jobqueue.yaml ~/.config/dask/jobqueue.yaml

# --- Add jupyter vim bindings
source $bash_envy/useful-cmd-line/enable_jupyter_vim_binding.sh
