#! /bin/bash

# --- Add key created in contrib to ssh-agent to use git
eval $(ssh-agent)

if [[ "$PW_CSP" == "gcp" || "$PW_CSP" == "google" ]] ; then
    ssh-add /contrib/Tim.Smith/.ssh/id_ed25519
elif [[ "$PW_CSP" == "aws" ]] ; then
    ssh-add /contrib/Tim.Smith/.ssh/id_rsa
fi

# --- Add basic environment stuff
echo "source /contrib/Tim.Smith/bash-envy/env/bashrc_master" >> ~/.bashrc
echo "source /contrib/Tim.Smith/bash-envy/env/vimrc" >> ~/.vimrc
echo "source-file /contrib/Tim.Smith/bash-envy/env/tmux.conf" >> ~/.tmux.conf
source ~/.bashrc

# --- Some git config
git config --global user.name "timothyas"
git config --global user.email "smith.timothy.andrew@gmail.com"
git config --global color.ui true
git config --global push.default simple

# --- Dask configuring
mkdir -p ~/.config/dask
cp /contrib/Tim.Smith/ddhf/pw/distributed.yaml ~/.config/dask/distributed.yaml
cp /contrib/Tim.Smith/ddhf/pw/dask.yaml ~/.config/dask/dask.yaml
if [[ "$PW_CSP" == "gcp" || "$PW_CSP" == "google" ]] ; then
    cp /contrib/Tim.Smith/ddhf/pw/jobqueue-c2-standard-60.yaml ~/.config/dask/jobqueue.yaml
elif [[ "$PW_CSP" == "aws" ]] ; then
    cp /contrib/Tim.Smith/ddhf/pw/jobqueue-m5zn-xl.yaml ~/.config/dask/jobqueue.yaml
fi

# --- Add jupyter vim bindings
source $bash_envy/useful-cmd-line/enable_jupyter_vim_binding.sh
cp $bash_envy/env/pw_jupyter_notebook_config.py ~/.jupyter/jupyter_notebook_config.py
