" master vimrc file
" Add this line to ~/.vimrc
"   source /path/to/thisfile

set number
set mouse=a
set viminfo='20,<1000
syntax on


set tabstop=4
set expandtab
set incsearch "" incremental search

" from lonestar
" I think this was for highlighted tabs in fortran
" leaving it out for now
" let fortran_have_tabs=1
" set term=screen-256color

" from pleiades, not sure on this one
" set backspace=indent,eol,start

" " This sets the tw to 80 when opening tex documents. Very useful for moving
" around
if !exists("autocommands_loaded")
	let autocommands_loaded=1 
	autocmd BufNewFile,BufRead *.tex set tw=80
endif 
" Same for *.rst documents
if !exists("autocommands_loaded")
	let autocommands_loaded=1 
	autocmd BufNewFile,BufRead *.rst set tw=80
endif 
